style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/pcanham/terraform-module-aws-vpc
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - docs
        - style
        - refactor
        - perf
        - test
        - build
        - ci
        - chore
        - revert
        - deprecated
        - security
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      docs: Documentation
      style: Styles
      refactor: Code Refactoring
      perf: Performance Improvements
      test: Tests
      build: Builds
      ci: Continuous Integrations
      chore: Chores
      revert: Reverts
      deprecated: Deprecated warning
      security: Security
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
